### ISSUE TITLE
Error Loading Tileset on Blender 2.79a MacOS

### ISSUE THREAD

**Issue by aranha92** [Sprytile/Sprytile#100]
Hello, I am currently getting the error below trying to load a Tileset with Sprytile on a fresh Blender 2.79a install. Sprytile version is 0.4.36 and macOS High Sierra 10.13.13. Seems similar to #87. Thanks for your work!
> Traceback (most recent call last):
>   File "/Users/gabriel/Library/Application Support/Blender/2.79/scripts/addons/SpryTile/sprytile_utils.py", line 745, in execute
>     SprytileLoadTileset.load_tileset_file(context, self.filepath)
>   File "/Users/gabriel/Library/Application Support/Blender/2.79/scripts/addons/SpryTile/sprytile_utils.py", line 755, in load_tileset_file
>     bpy.ops.sprytile.material_setup()
>   File "/Applications/blender.app/Contents/Resources/2.79/scripts/modules/bpy/ops.py", line 189, in __call__
>     ret = op_call(self.idname_py(), None, kw)
> RuntimeError: Operator bpy.ops.sprytile.material_setup.poll() failed, context is incorrect
> 
> location: <unknown location>:-1
> 
> location: <unknown location>:-1

**Comment by ChemiKhazi** [comment]
Thank you for this report. I don't have access to a Mac machine but I'll see what I can do.

**Comment by internetfett** [comment]
I was not able to reproduce this. Maybe something else specific to that machine?

<img width="596" alt="screen shot 2018-03-15 at 2 37 03 pm" src="https://user-images.githubusercontent.com/2441525/37487104-837b27aa-285e-11e8-9898-d117566618be.png">

**Comment by MattGuerrette** [comment]
I can confirm it is also present on Windows 10.

Blender v2.79 

![sprytile_issue](https://user-images.githubusercontent.com/6388953/37866967-525f5ba8-2f68-11e8-828a-df3cec5dafe4.png)

**Comment by ReiMari** [comment]
I got around this by having an object selected and then manually add a material to the cube before clicking load tileset. If I just have an object selected that doesn't have a material, then that error appears.

**Comment by ChemiKhazi** [comment]
It looks like this issue stemmed from the instructions being unclear on where to load the tilemaps and the code not being defensive enough about how to load tilemaps.

To load tilemaps, you must have a mesh object selected with a material on it. I think that part wasn't made clear enough in the instructions. The next release should have code that addresses this issue.

Thanks for all your reports!
