### ISSUE TITLE
Crash when placing tile. Tiles won't load on restart.

### ISSUE THREAD

**Issue by tylerzudans** [Sprytile/Sprytile#128]
Blender crashed while I was trying out sprytile. When I reopened, I had to re-enable the addon and got this message. The tile set wasn't visible, and when I tried to build a tile I got the same error below (but no crash this time) and no tile was built.

Traceback (most recent call last):
  File "C:\Users\tyler\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\SpryTile\sprytile_modal.py", line 608, in modal
    self.exit_modal(event, context)
  File "C:\Users\tyler\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\SpryTile\sprytile_modal.py", line 924, in exit_modal
    self.call_tool(event, False, context)
  File "C:\Users\tyler\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\SpryTile\sprytile_modal.py", line 712, in call_tool
    build_preview=self.draw_preview,
  File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\modules\bpy_types.py", line 713, in __getattribute__
    return super().__getattribute__(attr)
AttributeError: 'VIEW3D_OP_SprytileModalTool' object has no attribute 'draw_preview'

location: <unknown location>:-1

**Comment by tylerzudans** [comment]
Sprytile is working again, I did remove sprytile data, disabled the add-on, restarted blender, then enabled the addon again
